apiVersion: v1
kind: ConfigMap
metadata:
  name: kronos-config
  namespace: kube-system
data:
  config.yaml: |
    metricsProvider:
      type: "kepler"
      endpoint: "http://kepler-exporter-service.kepler.svc.cluster.local:9102/metrics"
    scheduler:
      port: 8000
      healthProbePort: 8080
      metricsBindAddress: ":8081"
      leaderElection:
        leaderElect: true
        resourceName: kronos-scheduler
