apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronos-scheduler
  namespace: kube-system
  labels:
    app: kronos-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronos-scheduler
  template:
    metadata:
      labels:
        app: kronos-scheduler
    spec:
      serviceAccountName: kronos-scheduler
      containers:
      - name: kronos-scheduler
        image: kronos-scheduler:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
