apiVersion: v1
kind: Service
metadata:
  name: kronos-scheduler
  namespace: kube-system
  labels:
    app: kronos-scheduler
spec:
  selector:
    app: kronos-scheduler
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
