# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization


# images:
#   - name: kronos-scheduler
#     newName: kronos-scheduler
#     newTag: latest
    
# # All core Kubernetes resources involved
# resources:
#   - manifests/kronos/rbac.yaml
#   - manifests/kronos/deployment.yaml
#   - manifests/kronos/service.yaml

# # ConfigMap containing scheduler config file
# configMapGenerator:
#   - name: kronos-scheduler-config
#     files:
#       - manifests/scheduler-config/scheduler-config.yaml

# generatorOptions:
#   disableNameSuffixHash: true


