apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: kronos-scheduler
      plugins:
        filter:
          enabled:
          - name: EnergyAware
        score:
          enabled:
          - name: EnergyAware
      pluginConfig:
      - name: EnergyAware
        args: {}
    leaderElection:
      leaderElect: true
      resourceName: kronos-scheduler
      resourceNamespace: kube-system
